### ISSUE TITLE
fatal error: scilab/stack-c.h: No such file or directory

### ISSUE THREAD

**Issue by TohQiQi** [ROBOTIS-GIT/ROBOTIS-Optimization#2]
I am using Ubuntu 18.04. When I catkin_make I get the error like this:
![Capture](https://user-images.githubusercontent.com/60141994/89096952-22b25f80-d40d-11ea-8206-f2007ed549e6.JPG)

Can I know how to solve this error?

**Comment by ROBOTIS-Will** [comment]
Hi, this package is only supported in Kinetic and not used anymore in OP3 as we implemented optimization code.
According to the error message, it looks like scilab is missing or version mismatch.

**Comment by TohQiQi** [comment]
> Hi, this package is only supported in Kinetic and not used anymore in OP3 as we implemented optimization code.
> According to the error message, it looks like scilab is missing or version mismatch.

Thank you for your reply. So now OP3 did not use optimization package or have another package to replace this package?

**Comment by ROBOTIS-Will** [comment]
I was told from the dev team engineer that the OP3 directly calculates data in the source code level in order to reduce the dependency.

**Comment by TohQiQi** [comment]
Alright, thank you very much
